# Generated by Django 5.2.10 on 2026-01-11 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('workspace_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_query', models.TextField()),
                ('assistant_answer', models.TextField(blank=True, default='')),
                ('route', models.CharField(blank=True, default='', max_length=64)),
                ('intent', models.CharField(blank=True, default='', max_length=128)),
                ('reasoning_trace', models.JSONField(blank=True, default=dict)),
                ('retrieval_meta', models.JSONField(blank=True, default=dict)),
                ('model_meta', models.JSONField(blank=True, default=dict)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=64)),
                ('warnings', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='conversation.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('statute', 'statute'), ('case', 'case'), ('guideline', 'guideline'), ('dmc', 'dmc'), ('other', 'other')], max_length=32)),
                ('source_id', models.CharField(max_length=255)),
                ('source_title', models.CharField(blank=True, default='', max_length=255)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('chunk_id', models.CharField(blank=True, default='', max_length=255)),
                ('supports_claim', models.BooleanField(default=True)),
                ('claim_id', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='conversation.turn')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conversatio_user_id_1fa293_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-created_at'], name='conversatio_created_bd0cae_idx'),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_f8704b_idx'),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['intent'], name='conversatio_intent_016059_idx'),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['route'], name='conversatio_route_bbffea_idx'),
        ),
        migrations.AddIndex(
            model_name='turn',
            index=models.Index(fields=['-created_at'], name='conversatio_created_9531e4_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['turn', 'rank'], name='conversatio_turn_id_e885e7_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['source_type', 'source_id'], name='conversatio_source__2f5f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['chunk_id'], name='conversatio_chunk_i_9d7504_idx'),
        ),
    ]
